element = input('Digite algo: ')
print(type(element))
print(element.isalnum)
print(element.isalpha)
print(element.isascii)
print(element.isdecimal)
print(element.isdigit)
print(element.isidentifier) 
print(element.islower)
print(element.isnumeric)
print(element.isprintable)
print(element.isspace)
print(element.istitle)
print(element.isupper)
