element = input('Digite algo: ')
print('O tipo primitivo é {}.' .format(type(element)))
print('É alfanúmerico? {}' .format(element.isalnum))
print('É alfabético? {}' .format(element.isalpha))
print('É um número? {}' .format(element.isnumeric))
print('É um decimal? {}' .format(element.isdecimal))
print('Só tem espaços? {}' .format(element.isspace))
print('É composto por dígitos? {}' .format(element.isdigit))
print('É um identificador válido? {}' .format(element.isidentifier))
print('Tem caracteres ASCII? {}' .format(element.isascii))
print('Pode ser impresso na tela? {}' .format(element.isprintable))
print('Está capitalizada? {}' .format(element.istitle))
print('Está em maiúscula? {}' .format(element.isupper))
print('Está em minúscula? {}' .format(element.islower))
