# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
numero = int(input('Digite um número inteiro qualquer: '))
print('Tabuada do número {}.'.format(numero)
print('0 x {}'.format(numero*0))
print('1 x {}'.format(numero*1))
print('2 x {}'.format(numero*2))
print('3 x {}'.format(numero*3))
print('4 x {}'.format(numero*4))
print('5 x {}'.format(numero*5))
print('6 x {}'.format(numero*6))
print('7 x {}'.format(numero*7))
print('8 x {}'.format(numero*8))
print('9 x {}'.format(numero*9))
print('10 x {}'.format(numero*10))